
[pets]

	[pets.displays]
		cap_dolphin_pet_display = true
		dolphin_pet_display = false

	[pets.quality_of_life]
		autopet_message_hider = 0
		hide_pet_nametags = false
		pet_item_confirmation = false

[general]

	[general.other]
		config_button_on_pause = true
		reopen_options_menu = true
		first_launch = false

	[general.reparty]
		override_other_reparty_commands = true
		auto-accept_reparty_timeout = 60
		auto-accept_reparty = false

	[general.command_aliases]
		command_alias_mode = 0

	[general.api]
		hypixel_api_key = ""
		skytils_data = "https://raw.githubusercontent.com/Skytils/SkytilsMod-Data/main/"

	[general.updates]
		update_channel = 2

[miscellaneous]

	[miscellaneous.other]
		transparent_head_layer = 100
		cap_legion_display = true
		endstone_protector_spawn_timer = false
		legion_player_display = false
		placed_summoning_eye_display = false

	[miscellaneous.items]
		larger_heads = 100
		soul_eater_bonus = false
		compact_item_stars = false
		show_npc_sell_price = false
		dropped_item_scale = 100
		show_potion_tier = false
		show_enchanted_book_tier = false
		hide_implosion_particles = false
		hide_midas_staff_gold = false
		prevent_placing_weapons = false
		show_pet_candies = false

	[miscellaneous.item_rarity]
		item_rarity_opacity = 75
		show_item_rarity = false
		show_pet_rarity = false

	[miscellaneous.minions]
		only_collect_enchanted_items = false
		show_minion_tier = false

	[miscellaneous.quality_of_life]
		boss_bar_fix = false
		hide_jerry_rune = false
		highlight_dungeon-sellable_items = false
		show_arachne_spawn = false
		middle_click_gui_items = false
		show_lowest_bin_price = false
		dungeon_pot_lock = 0
		hide_fire_on_entities = false
		highlight_salvageable_items = false
		prevent_log_spam = false
		no_hurtcam = false
		power_orb_lock = false
		show_coins_per_bit = false
		stop_clicking_non-salvageable_items = false
		hide_fishing_hooks = false
		trick_or_treat_chest_alert = false
		view_relic_waypoints = false
		custom_damage_splash = false
		enchant_glint_fix = false
		hide_air_display = false
		find_rare_relics = false
		hide_mob_death_particles = false
		hide_lightning = false
		disable_night_vision = false
		no_fire = false
		show_arachne_hp = false
		custom_auction_price_input = false
		protect_starred_items = false

[slayer]

	[slayer.quality_of_life]
		slayer_miniboss_spawn_alert = false
		slayer_boss_hitbox = false
		ping_when_in_atoned_horror_danger_zone = false

[sounds]

	[sounds.abilities]
		disable_cooldown_sounds = false
		disable_jerry-chine_gun_sounds = false
		disable_flower_of_truth_sounds = false

	[sounds.dungeons]
		disable_terracotta_sounds = false

[dungeons]

	[dungeons.miscellaneous]
		auto_copy_fails_to_clipboard = false
		dungeon_timer = false
		necron_phase_timer = false
		dungeon_chest_profit = false

	[dungeons.terminal_solvers]
		click_in_order_solver = false
		starts_with_sequence_solver = false
		select_all_colors_solver = false
		simon_says_solver = false

	[dungeons.score_calculation]
		receive_help_for_secret_counts = false
		show_dungeon_score_estimate = false
		score_calculation_party_assist = false
		remove_party_chat_notification_sounds = false

	[dungeons.quality_of_life]
		spirit_leap_names = false
		hide_floor_4_crowd_messages = false
		larger_bat_models = false
		show_bat_hitboxes = false
		hide_damage_in_boss = false
		hide_non-starred_mobs_nametags = false
		revive_stone_names = false
		hide_wither_miner_nametags = false
		"show_sadan's_interest" = false
		hide_terminal_completion_titles = false
		hide_terracotta_nametags = false
		show_giant_hp = false
		box_skeleton_masters = false
		dungeon_chest_reroll_confirmation = 0
		hide_spirit_animal_nametags = false
		"show_necron's_hp" = 0
		hide_oruo_messages = false

	[dungeons.solvers]
		blaze_solver = false
		boulder_solver = false
		ice_fill_solver = false
		ice_path_solver = false
		show_next_blaze = false
		water_board_solver = false
		find_correct_livid = false
		teleport_maze_solver = false
		three_weirdos_solver = false
		trivia_solver = false

[farming]

	[farming.quality_of_life]
		hide_farming_rng_titles = false

[mining]

	[mining.quality_of_life]
		powder_ghast_ping = false
		raffle_warning = false
		dark_mode_mist = false
		recolor_carpets = false
		raffle_waypoint = false

	[mining.solvers]
		puzzler_solver = false
		fetchur_solver = false

[spam]

	[spam.abilities]
		implosion_hider = 0
		ray_of_hope_hider = 0
		midas_staff_hider = 0
		spirit_sceptre_hider = 0
		giant_sword_hider = 0
		livid_dagger_hider = 0
		mana_use_hider = 0

	[spam.miscellaneous]
		blocks_in_the_way_hider = 0
		combo_hider = 0
		out_of_mana_hider = 0
		no_enemies_nearby_hider = 0
		"can't_use_ability_hider" = 0
		profile_message_hider = 0
		compact_building_tools = false
		cooldown_hider = 0

	[spam.display]
		text_shadow = 0

	[spam.dungeons]
		blessing_hider = 0
		boss_messages_hider = 0
		superboom_pickup_hider = 0
		self_orb_pickup_hider = 0
		blood_key_hider = 0
		toast_time = 2500
		dungeon_abilities_messages_hider = 0
		tether_hider = 0
		other_orb_pickup_hider = 0
		countdown_and_ready_messages_hider = 0
		revive_stone_pickup_hider = 0
		wither_key_hider = 0
		mort_messages_hider = 0

	[spam.fishing]
		blessing_enchant_hider = 0
		blessing_bait_hider = 0

[events]

	[events.mayor_jerry]
		hidden_jerry_alert = false

	[events.mythological]
		burrow_particle_add-on = false
		show_griffin_burrows = false
		show_fast-travel_addon = false
		show_time_until_burrow_refresh = false

